CREATE TABLE "Users" (
  "user_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(100),
  "dob" date,
  "email" varchar(100) UNIQUE,
  "phone" varchar(20),
  "nid" varchar(50) UNIQUE,
  "address" text,
  "created_at" timestamp
);

CREATE TABLE "Doctors" (
  "user_id" int UNIQUE,
  "doctor_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "custom_doctor_id" varchar(50) UNIQUE,
  "department" varchar(100),
  "specialization" varchar(100),
  "consultation_fee" decimal(10,2)
);

CREATE TABLE "Doctor_Degrees" (
  "degree_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "doctor_id" int,
  "degree_name" varchar(100),
  "field_of_study" varchar(100),
  "achievement_year" int,
  "institution" varchar(150)
);

CREATE TABLE "Doctor_Surgeries" (
  "surgery_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "doctor_id" int,
  "surgery_name" varchar(100),
  "surgery_fee" decimal(10,2)
);

CREATE TABLE "Doctor_Schedule" (
  "schedule_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "doctor_id" int,
  "day_of_week" varchar(15),
  "start_time" time,
  "end_time" time
);

CREATE TABLE "Patients" (
  "user_id" int UNIQUE,
  "patient_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "custom_patient_id" varchar(50) UNIQUE,
  "height_cm" decimal(5,2),
  "weight_kg" decimal(5,2),
  "blood_group" varchar(5),
  "allergies" text,
  "medical_conditions" text,
  "disabilities" text,
  "disability_details" text
);

CREATE TABLE "Hospitals" (
  "hospital_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "admin_user_id" int,
  "name" varchar(150),
  "est_year" int,
  "email" varchar(100),
  "phone" varchar(20),
  "address" text,
  "license_number" varchar(50),
  "tin" varchar(50)
);

CREATE TABLE "Hospital_Departments" (
  "dept_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "hospital_id" int,
  "dept_name" varchar(100),
  "specialization" varchar(100)
);

CREATE TABLE "Hospital_Operations" (
  "op_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "dept_id" int,
  "operation_name" varchar(100),
  "price" decimal(10,2)
);

CREATE TABLE "Hospital_Tests" (
  "test_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "dept_id" int,
  "test_name" varchar(100),
  "price" decimal(10,2)
);

CREATE TABLE "Hospital_Doctors" (
  "hospital_id" int,
  "doctor_id" int,
  "consultation_fee" decimal(10,2)
);

CREATE TABLE "Hospital_Staff" (
  "staff_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "hospital_id" int,
  "role" varchar(20),
  "eid" varchar(50),
  "monthly_salary" decimal(10,2),
  "phone" varchar(20)
);

CREATE TABLE "Chambers" (
  "chamber_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "doctor_id" int,
  "name" varchar(150),
  "est_year" int,
  "email" varchar(100),
  "phone" varchar(20),
  "address" text
);

CREATE TABLE "Chamber_Assistants" (
  "assistant_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "chamber_id" int,
  "eid" varchar(50),
  "monthly_salary" decimal(10,2),
  "phone" varchar(20)
);

CREATE TABLE "Appointments" (
  "appointment_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "patient_id" int,
  "hospital_id" int,
  "doctor_id" int,
  "chamber_id" int,
  "appt_date" date,
  "appt_time" time,
  "short_note" text,
  "status" varchar(20)
);

CREATE TABLE "Prescriptions" (
  "prescription_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "appointment_id" int,
  "medicine_name" varchar(100),
  "dosage" varchar(50),
  "time_instruction" varchar(50),
  "duration" varchar(50)
);

CREATE TABLE "Pharmacies" (
  "pharmacy_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" int UNIQUE,
  "name" varchar(150),
  "phone" varchar(20),
  "address" text
);

CREATE TABLE "Pharmacy_Medicines" (
  "medicine_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "pharmacy_id" int,
  "name" varchar(100),
  "quantity" int,
  "price" decimal(10,2),
  "expiry_date" date
);

CREATE TABLE "Medical_History" (
  "history_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "patient_id" int,
  "doctor_id" int,
  "visit_date" date,
  "diagnosis" text,
  "notes" text
);

COMMENT ON TABLE "Hospital_Doctors" IS 'Composite Primary Key (hospital_id, doctor_id)';

ALTER TABLE "Doctors" ADD FOREIGN KEY ("user_id") REFERENCES "Users" ("user_id");

ALTER TABLE "Doctor_Degrees" ADD FOREIGN KEY ("doctor_id") REFERENCES "Doctors" ("doctor_id");

ALTER TABLE "Doctor_Surgeries" ADD FOREIGN KEY ("doctor_id") REFERENCES "Doctors" ("doctor_id");

ALTER TABLE "Doctor_Schedule" ADD FOREIGN KEY ("doctor_id") REFERENCES "Doctors" ("doctor_id");

ALTER TABLE "Patients" ADD FOREIGN KEY ("user_id") REFERENCES "Users" ("user_id");

ALTER TABLE "Hospitals" ADD FOREIGN KEY ("admin_user_id") REFERENCES "Users" ("user_id");

ALTER TABLE "Hospital_Departments" ADD FOREIGN KEY ("hospital_id") REFERENCES "Hospitals" ("hospital_id");

ALTER TABLE "Hospital_Operations" ADD FOREIGN KEY ("dept_id") REFERENCES "Hospital_Departments" ("dept_id");

ALTER TABLE "Hospital_Tests" ADD FOREIGN KEY ("dept_id") REFERENCES "Hospital_Departments" ("dept_id");

ALTER TABLE "Hospital_Doctors" ADD FOREIGN KEY ("hospital_id") REFERENCES "Hospitals" ("hospital_id");

ALTER TABLE "Hospital_Doctors" ADD FOREIGN KEY ("doctor_id") REFERENCES "Doctors" ("doctor_id");

ALTER TABLE "Hospital_Staff" ADD FOREIGN KEY ("hospital_id") REFERENCES "Hospitals" ("hospital_id");

ALTER TABLE "Chambers" ADD FOREIGN KEY ("doctor_id") REFERENCES "Doctors" ("doctor_id");

ALTER TABLE "Chamber_Assistants" ADD FOREIGN KEY ("chamber_id") REFERENCES "Chambers" ("chamber_id");

ALTER TABLE "Appointments" ADD FOREIGN KEY ("patient_id") REFERENCES "Patients" ("patient_id");

ALTER TABLE "Appointments" ADD FOREIGN KEY ("hospital_id") REFERENCES "Hospitals" ("hospital_id");

ALTER TABLE "Appointments" ADD FOREIGN KEY ("doctor_id") REFERENCES "Doctors" ("doctor_id");

ALTER TABLE "Prescriptions" ADD FOREIGN KEY ("appointment_id") REFERENCES "Appointments" ("appointment_id");

ALTER TABLE "Pharmacies" ADD FOREIGN KEY ("user_id") REFERENCES "Users" ("user_id");

ALTER TABLE "Pharmacy_Medicines" ADD FOREIGN KEY ("pharmacy_id") REFERENCES "Pharmacies" ("pharmacy_id");

ALTER TABLE "Medical_History" ADD FOREIGN KEY ("patient_id") REFERENCES "Patients" ("patient_id");

ALTER TABLE "Medical_History" ADD FOREIGN KEY ("doctor_id") REFERENCES "Doctors" ("doctor_id");
