DROP TABLE IF EXISTS "Medical_History" CASCADE;
DROP TABLE IF EXISTS "Pharmacy_Medicines" CASCADE;
DROP TABLE IF EXISTS "Pharmacies" CASCADE;
DROP TABLE IF EXISTS "Prescriptions" CASCADE;
DROP TABLE IF EXISTS "Appointments" CASCADE;
DROP TABLE IF EXISTS "Chamber_Assistants" CASCADE;
DROP TABLE IF EXISTS "Chambers" CASCADE;
DROP TABLE IF EXISTS "Hospital_Staff" CASCADE;
DROP TABLE IF EXISTS "Hospital_Doctors" CASCADE;
DROP TABLE IF EXISTS "Hospital_Tests" CASCADE;
DROP TABLE IF EXISTS "Hospital_Operations" CASCADE;
DROP TABLE IF EXISTS "Hospital_Departments" CASCADE;
DROP TABLE IF EXISTS "Hospitals" CASCADE;
DROP TABLE IF EXISTS "Patients" CASCADE;
DROP TABLE IF EXISTS "Doctor_Schedule" CASCADE;
DROP TABLE IF EXISTS "Doctor_Surgeries" CASCADE;
DROP TABLE IF EXISTS "Doctor_Degrees" CASCADE;
DROP TABLE IF EXISTS "Doctors" CASCADE;
DROP TABLE IF EXISTS "Users" CASCADE;

CREATE TABLE "Users" (
    "user_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "name" varchar(100),
    "dob" date,
    "email" varchar(100) UNIQUE,
    "phone" varchar(20),
    "nid" varchar(50) UNIQUE,
    "address" text,
    "created_at" timestamp DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE "Doctors" (
    "user_id" int UNIQUE,
    "doctor_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "custom_doctor_id" varchar(50) UNIQUE,
    "department" varchar(100),
    "specialization" varchar(100),
    "consultation_fee" decimal(10, 2)
);

CREATE TABLE "Doctor_Degrees" (
    "degree_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "doctor_id" int NOT NULL REFERENCES "Doctors"("doctor_id") ON DELETE CASCADE
    "degree_name" varchar(100),
    "institution" varchar(150),
    "achievement_year" int,
    "field_of_study" varchar(100)
);

CREATE TABLE "Doctor_Surgeries" (
    "surgery_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "doctor_id" int NOT NULL REFERENCES "Doctors"("doctor_id") ON DELETE CASCADE,
    "surgery_name" varchar(100),
    "surgery_fee" decimal(10, 2)
);

CREATE TABLE "Doctor_Schedule" (
    "schedule_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "doctor_id" int NOT NULL REFERENCES "Doctors"("doctor_id") ON DELETE CASCADE,
    "day_of_week" varchar(10),
    "start_time" time,
    "end_time" time
);

CREATE TABLE "Patients" (

);
