DROP TABLE IF EXISTS "Medical_History" CASCADE;
DROP TABLE IF EXISTS "Pharmacy_Medicines" CASCADE;
DROP TABLE IF EXISTS "Pharmacies" CASCADE;
DROP TABLE IF EXISTS "Prescriptions" CASCADE;
DROP TABLE IF EXISTS "Appointments" CASCADE;
DROP TABLE IF EXISTS "Chamber_Assistants" CASCADE;
DROP TABLE IF EXISTS "Chambers" CASCADE;
DROP TABLE IF EXISTS "Hospital_Staff" CASCADE;
DROP TABLE IF EXISTS "Hospital_Doctors" CASCADE;
DROP TABLE IF EXISTS "Hospital_Tests" CASCADE;
DROP TABLE IF EXISTS "Hospital_Operations" CASCADE;
DROP TABLE IF EXISTS "Hospital_Departments" CASCADE;
DROP TABLE IF EXISTS "Hospitals" CASCADE;
DROP TABLE IF EXISTS "Patients" CASCADE;
DROP TABLE IF EXISTS "Doctor_Schedule" CASCADE;
DROP TABLE IF EXISTS "Doctor_Surgeries" CASCADE;
DROP TABLE IF EXISTS "Doctor_Degrees" CASCADE;
DROP TABLE IF EXISTS "Doctors" CASCADE;
DROP TABLE IF EXISTS "Users" CASCADE;

CREATE TABLE "Users" (
    "user_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "name" varchar(100),
    "dob" date,
    "email" varchar(100) UNIQUE,
    "phone" varchar(20),
    "nid" varchar(50) UNIQUE,
    "address" text,
    "created_at" timestamp DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE "Doctors" (
    "user_id" int UNIQUE,
    "doctor_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
)
